[package]
name = "numcodecs-qpet-sperr-py"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

description = "QPET-SPERR codec for the numcodecs API"
readme = "README.md"
categories = ["compression", "encoding"]
keywords = ["QPET-SPERR", "numcodecs", "compression", "encoding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "numcodecs_qpet_sperr"
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
numcodecs = { workspace = true }
numcodecs-python = { workspace = true }
numcodecs-qpet-sperr = { workspace = true }
pyo3 = { workspace = true, features = ["macros", "abi3-py310"] }
