[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "numcodecs_qpet"
version = "0.1.0"

readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.10"

dependencies = [
    "numcodecs>=0.13.0,<0.17",
]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[dependency-groups]
dev = ["ruff~=0.9.0"]

[tool.maturin]
python-source = "py"
module-name = "numcodecs_qpet._qpet"
features = ["pyo3/extension-module"]
